P1 : main.o sistEntrada.o anaLexico.o anaSintactico.o tablaSimbolos.o gestErrores.o
	gcc -o P1 main.o sistEntrada.o anaLexico.o anaSintactico.o tablaSimbolos.o gestErrores.o


	rm main.o sistEntrada.o anaLexico.o anaSintactico.o tablaSimbolos.o gestErrores.o
	
