P1 : main.o sistEntrada.o anaLexico.o anaSintactico.o tablaSimbolos.o gestErrores.o
	gcc -o P1 main.o sistEntrada.o anaLexico.o anaSintactico.o tablaSimbolos.o gestErrores.o
	gcc -c anaLexico.c 
	gcc -c main.c 
	gcc -c sistEntrada.c 
	gcc -c anaSintactico.c 
	gcc -c tablaSimbolos.c 
	gcc -c gestErrores.c

	rm main.o sistEntrada.o anaLexico.o anaSintactico.o tablaSimbolos.o gestErrores.o
	
